name: food_delivery_app
description: food_delivery_app

version: 2.7.0+1

environment:
  sdk: ">=3.7.0-323.0.dev <4.0.0" # Your SDK constraint
  flutter: ^3.10.5                # Your Flutter constraint (ensure your Flutter install matches this range)

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6 # Updated
  google_maps_flutter: ^2.5.3 # Updated
  mvc_pattern: ^8.12.0 # Updated (check for any breaking changes if you use this heavily)
  global_configuration: ^2.0.0 # No -nullsafety suffix needed for recent versions
  infinite_scroll_pagination: ^4.0.0 # Updated (check for Material 3 text style changes)
  html: ^0.15.4 # Check latest, this one doesn't change as often
  shared_preferences: ^2.2.2 # Updated
  flutter_html: ^3.0.0-beta.2 # Using beta as full 3.0.0 might not be out or stable, check pub.dev
  flutter_svg: ^2.0.9 # Updated
  location: ^5.0.3 # Updated
  webview_flutter: ^4.12.0 # Updated
  url_launcher: ^6.2.5 # Updated
  cached_network_image: ^3.3.1 # Updated (this had DecoderCallback issues)
  fluttertoast: ^8.2.9 # Switched to pub.dev version, Updated
  flutter_staggered_grid_view: ^0.7.0 # Updated
  intl_utils: ^2.8.7 # Updated
  intl: ^0.19.0
#  font_awesome_flutter: ^10.5.0
  flutter_dash: ^1.0.0
  dotted_line: ^3.0.1

  ## Firebase - Update all to be compatible and recent
  firebase_core: ^3.13.0 # Updated
  firebase_auth: ^5.5.3 # Updated
  firebase_messaging: ^15.2.5 # Updated
  cloud_firestore: ^5.6.7 # Updated
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.2
  Ù€sign_in_with_apple: ^5.0.0
  http: ^1.1.0

  flutter_native_splash: ^2.3.10 # Updated (Note: color format "6a1b9a" should be "0x6a1b9a" or "6A1B9A" if that was an issue)
  map_launcher: ^3.2.1 # Updated
  flutter_credit_card: ^4.0.1 # Seems recent, check if newer exists
  flutter_svg_provider: ^1.0.7 # Updated (this had hashValues issues)
  pin_code_fields: ^8.0.1 # Seems recent, check if newer exists
  permission_handler: ^11.3.0 # Updated
  collection: ^1.18.0 # Updated (usually updated with Dart SDK)
  carousel_slider: ^5.0.0
  chucker_flutter: ^1.8.5


  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.1
  bot_toast: ^4.1.3
  # get user location
  geolocator: ^14.0.1 # Updated
  geocoding: ^3.0.0



dev_dependencies:
  flutter_launcher_icons: ^0.13.1 # Updated
  flutter_test:
    sdk: flutter

# Consider if this override is still needed with updated firebase_core
dependency_overrides:
  firebase_core_platform_interface: 4.8.0 # Try updating this or removing if firebase_core itself is recent enough

flutter_native_splash:
  image: assets/img/carry_eats_hub_splash.png
  # color: "6a1b9a" # Correct format is usually "0xFF6A1B9A" or just "6A1B9A" for hex
  color: "6A1B9A" # Or "0xFF6A1B9A"
  android: true
  fill: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/cfg/
    - assets/img/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/nunito/Nunito-Black.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
          weight: 100
        # Corrected duplicate ExtraLight for weight 200
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 200
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/cairo/Cairo-Black.ttf
          weight: 900

flutter_intl:
  enabled: true
